export default {
  departments: [
    '서비스본부',
    '경영지원본부',
    '전략사업본부',
    '서비스센터',
    '고객지원팀',
    '기술지원1팀',
    '기술지원2팀',
    '기획운영팀',
    '디지털전략팀',
    '물류팀',
    '영업관리팀',
    '원격지원팀',
    '파트너사업팀',
    '회계팀',
    'tBoard개발팀',
    '홍보팀',
    '기술지원팀',
    '기술/영업팀',
    '경영지원팀',
    '전략사업팀',
    '상품기획팀',
  ],
  positions: [
    '본부장',
    '센터장',
    '팀장',
    '팀원',
    '지사장',
  ],
  members: [
    {
      department: '서비스본부',
      position: '본부장',
      name: '김동현',
      img: '/static/members/zeu.png',
    },
    {
      department: '경영지원본부',
      position: '본부장',
      name: '이왕규',
      img: '/static/members/zeu.png',
    },
    {
      department: '전략사업본부',
      position: '본부장',
      name: '이준승',
      img: '/static/members/zeu.png',
    },
    {
      department: '서비스센터',
      position: '센터장',
      name: '정득헌',
      img: '/static/members/zeu.png',
    },
    {
      department: '고객지원팀',
      position: '팀장',
      name: '황우현',
      img: '/static/members/zeu.png',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '전희현',
      img: '/static/members/zeu.png',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '김수지',
      img: '/static/members/zeu.png',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '문진아',
      img: '/static/members/zeu.png',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '송정화',
      img: '/static/members/zeu.png',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '김희진',
      img: '/static/members/zeu.png',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '이정희',
      img: '/static/members/zeu.png',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '송진아',
      img: '/static/members/zeu.png',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '민수현',
      img: '/static/members/zeu.png',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '허진',
      img: '/static/members/zeu.png',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '김상완',
      img: '/static/members/zeu.png',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '김부진',
      img: '/static/members/zeu.png',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '이성곤',
      img: '/static/members/zeu.png',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '김미경',
      img: '/static/members/zeu.png',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '최희정',
      img: '/static/members/zeu.png',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '백은지',
      img: '/static/members/zeu.png',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '양혜경',
      img: '/static/members/zeu.png',
    },
    {
      department: '기술지원1팀',
      position: '팀장',
      name: '김민수',
      img: '/static/members/zeu.png',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '김해원',
      img: '/static/members/zeu.png',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '김태흥',
      img: '/static/members/zeu.png',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '양근혁',
      img: '/static/members/zeu.png',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '장두성',
      img: '/static/members/zeu.png',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '김윤태',
      img: '/static/members/zeu.png',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '최정훈',
      img: '/static/members/zeu.png',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '김용운',
      img: '/static/members/zeu.png',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '이준',
      img: '/static/members/zeu.png',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '전명훈',
      img: '/static/members/zeu.png',
    },
    {
      department: '기술지원2팀',
      position: '팀장',
      name: '고준환',
      img: '/static/members/zeu.png',
    },
    {
      department: '기술지원2팀',
      position: '팀원',
      name: '백형식',
      img: '/static/members/zeu.png',
    },
    {
      department: '기술지원2팀',
      position: '팀원',
      name: '우상재',
      img: '/static/members/zeu.png',
    },
    {
      department: '기술지원2팀',
      position: '팀원',
      name: '강윤호',
      img: '/static/members/zeu.png',
    },
    {
      department: '기술지원2팀',
      position: '팀원',
      name: '김영범',
      img: '/static/members/zeu.png',
    },
    {
      department: '기술지원2팀',
      position: '팀원',
      name: '이진웅',
      img: '/static/members/zeu.png',
    },
    {
      department: '기술지원2팀',
      position: '팀원',
      name: '박현철',
      img: '/static/members/zeu.png',
    },
    {
      department: '기획운영팀',
      position: '팀원',
      name: '박경애',
      img: '/static/members/zeu.png',
    },
    {
      department: '기획운영팀',
      position: '팀원',
      name: '황유정',
      img: '/static/members/zeu.png',
    },
    {
      department: '디지털전략팀',
      position: '팀장',
      name: '한민우',
      img: '/static/members/zeu.png',
    },
    {
      department: '디지털전략팀',
      position: '팀원',
      name: '박서연',
      img: '/static/members/zeu.png',
    },
    {
      department: '물류팀',
      position: '팀장',
      name: '김윤곤',
      img: '/static/members/zeu.png',
    },
    {
      department: '물류팀',
      position: '팀원',
      name: '김영훈',
      img: '/static/members/zeu.png',
    },
    {
      department: '물류팀',
      position: '팀원',
      name: '심다영',
      img: '/static/members/zeu.png',
    },
    {
      department: '물류팀',
      position: '팀원',
      name: '이시우',
      img: '/static/members/zeu.png',
    },
    {
      department: '물류팀',
      position: '팀원',
      name: '김기원',
      img: '/static/members/zeu.png',
    },
    {
      department: '물류팀',
      position: '팀원',
      name: '김상태',
      img: '/static/members/zeu.png',
    },
    {
      department: '물류팀',
      position: '팀원',
      name: '정경학',
      img: '/static/members/zeu.png',
    },
    {
      department: '영업관리팀',
      position: '팀장',
      name: '김영삼',
      img: '/static/members/zeu.png',
    },
    {
      department: '영업관리팀',
      position: '팀원',
      name: '이미라',
      img: '/static/members/zeu.png',
    },
    {
      department: '영업관리팀',
      position: '팀원',
      name: '정용현',
      img: '/static/members/zeu.png',
    },
    {
      department: '영업관리팀',
      position: '팀원',
      name: '김문수',
      img: '/static/members/zeu.png',
    },
    {
      department: '영업관리팀',
      position: '팀원',
      name: '김승배',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀장',
      name: '최효승',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '임승현',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '박규호',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '박명갑',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '이정대',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '이한근',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '정성기',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '하태준',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '김윤형',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '김선미',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '김양순',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '서현정',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '신경진',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '박재혁',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '문종헌',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '강우현',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '성준호',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '주재형',
      img: '/static/members/zeu.png',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '김양화',
      img: '/static/members/zeu.png',
    },
    {
      department: '파트너사업팀',
      position: '팀장',
      name: '이영수',
      img: '/static/members/zeu.png',
    },
    {
      department: '파트너사업팀',
      position: '팀원',
      name: '황선혜',
      img: '/static/members/zeu.png',
    },
    {
      department: '파트너사업팀',
      position: '팀원',
      name: '윤인애',
      img: '/static/members/zeu.png',
    },
    {
      department: '회계팀',
      position: '팀장',
      name: '김진영',
      img: '/static/members/zeu.png',
    },
    {
      department: '회계팀',
      position: '팀원',
      name: '장은희',
      img: '/static/members/zeu.png',
    },
    {
      department: '회계팀',
      position: '팀원',
      name: '조주용',
      img: '/static/members/zeu.png',
    },
    {
      department: 'tBoard개발팀',
      position: '팀장',
      name: '홍민기',
      img: '/static/members/zeu.png',
    },
    {
      department: 'tBoard개발팀',
      position: '팀원',
      name: '최지현',
      img: '/static/members/zeu.png',
    },
    {
      department: 'tBoard개발팀',
      position: '팀원',
      name: '문병수',
      img: '/static/members/zeu.png',
    },
    {
      department: 'tBoard개발팀',
      position: '팀원',
      name: 'Jordy Ruiter',
      img: '/static/members/zeu.png',
    },
    {
      department: '홍보팀',
      position: '팀장',
      name: '하원기',
      img: '/static/members/zeu.png',
    },
    {
      department: '홍보팀',
      position: '팀원',
      name: '이의현',
      img: '/static/members/zeu.png',
    },
  ],
};
