export default {
  departments: [
    '서비스본부',
    '경영지원본부',
    '전략사업본부',
    '서비스센터',
    '고객지원팀',
    '기술지원1팀',
    '기술지원2팀',
    '기획운영팀',
    '디지털전략팀',
    '물류팀',
    '영업관리팀',
    '원격지원팀',
    '파트너사업팀',
    '회계팀',
    'tBoard개발팀',
    '홍보팀',
    '기술지원팀',
    '기술/영업팀',
    '경영지원팀',
    '전략사업팀',
    '상품기획팀',
  ],
  positions: [
    '본부장',
    '센터장',
    '팀장',
    '팀원',
    '지사장',
  ],
  members: [
    {
      department: '서비스본부',
      position: '본부장',
      name: '김동현',
      img: '/static/members/서비스본부_김동현.jpg',
    },
    {
      department: '경영지원본부',
      position: '본부장',
      name: '이왕규',
      img: '/static/members/경영지원본부_이왕규.jpg',
    },
    {
      department: '서비스센터',
      position: '센터장',
      name: '정득헌',
      img: '/static/members/서비스센터_정득헌.jpg',
    },
    {
      department: '고객지원팀',
      position: '팀장',
      name: '황우현',
      img: '/static/members/고객지원팀_황우현.jpg',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '전희현',
      img: '/static/members/고객지원팀_전희현.jpg',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '김수지',
      img: '/static/members/고객지원팀_김수지.jpg',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '문진아',
      img: '/static/members/고객지원팀_문진아.jpg',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '송정화',
      img: '/static/members/고객지원팀_송정화.jpg',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '김희진',
      img: '/static/members/고객지원팀_김희진.jpg',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '이정희',
      img: '/static/members/고객지원팀_이정희.jpg',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '송진아',
      img: '/static/members/고객지원팀_송진아.jpg',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '민수현',
      img: '/static/members/고객지원팀_민수현.jpg',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '허진',
      img: '/static/members/고객지원팀_허진.jpg',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '김상완',
      img: '/static/members/고객지원팀_김상완.jpg',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '김부진',
      img: '/static/members/고객지원팀_김부진.jpg',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '이성곤',
      img: '/static/members/고객지원팀_이성곤.jpg',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '김미경',
      img: '/static/members/고객지원팀_김미경.jpg',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '최희정',
      img: '/static/members/고객지원팀_최희정.jpg',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '백은지',
      img: '/static/members/고객지원팀_백은지.jpg',
    },
    {
      department: '고객지원팀',
      position: '팀원',
      name: '양혜경',
      img: '/static/members/고객지원팀_양혜경.jpg',
    },
    {
      department: '기술지원1팀',
      position: '팀장',
      name: '김민수',
      img: '/static/members/기술지원1팀_김민수.jpg',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '김해원',
      img: '/static/members/기술지원1팀_김해원.jpg',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '김태흥',
      img: '/static/members/기술지원1팀_김태흥.jpg',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '양근혁',
      img: '/static/members/기술지원1팀_양근혁.jpg',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '장두성',
      img: '/static/members/기술지원1팀_장두성.jpg',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '김윤태',
      img: '/static/members/기술지원1팀_김윤태.jpg',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '최정훈',
      img: '/static/members/기술지원1팀_최정훈.jpg',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '김용운',
      img: '/static/members/기술지원1팀_김용운.jpg',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '이준',
      img: '/static/members/기술지원1팀_이준.jpg',
    },
    {
      department: '기술지원1팀',
      position: '팀원',
      name: '전명훈',
      img: '/static/members/기술지원1팀_전명훈.jpg',
    },
    {
      department: '기술지원2팀',
      position: '팀장',
      name: '고준환',
      img: '/static/members/기술지원2팀_고준환.jpg',
    },
    {
      department: '기술지원2팀',
      position: '팀원',
      name: '백형식',
      img: '/static/members/기술지원2팀_백형식.jpg',
    },
    {
      department: '기술지원2팀',
      position: '팀원',
      name: '우상재',
      img: '/static/members/기술지원2팀_우상재.jpg',
    },
    {
      department: '기술지원2팀',
      position: '팀원',
      name: '강윤호',
      img: '/static/members/기술지원2팀_강윤호.jpg',
    },
    {
      department: '기술지원2팀',
      position: '팀원',
      name: '김영범',
      img: '/static/members/기술지원2팀_김영범.jpg',
    },
    {
      department: '기술지원2팀',
      position: '팀원',
      name: '이진웅',
      img: '/static/members/기술지원2팀_이진웅.jpg',
    },
    {
      department: '기술지원2팀',
      position: '팀원',
      name: '박현철',
      img: '/static/members/기술지원2팀_박현철.jpg',
    },
    {
      department: '기획운영팀',
      position: '팀원',
      name: '박경애',
      img: '/static/members/기획운영팀_박경애.jpg',
    },
    {
      department: '기획운영팀',
      position: '팀원',
      name: '황유정',
      img: '/static/members/기획운영팀_황유정.jpg',
    },
    {
      department: '디지털전략팀',
      position: '팀장',
      name: '한민우',
      img: '/static/members/디지털전략팀_한민우.jpg',
    },
    {
      department: '디지털전략팀',
      position: '팀원',
      name: '박서연',
      img: '/static/members/디지털전략팀_박서연.jpg',
    },
    {
      department: '물류팀',
      position: '팀장',
      name: '김윤곤',
      img: '/static/members/물류팀_김윤곤.jpg',
    },
    {
      department: '물류팀',
      position: '팀원',
      name: '김영훈',
      img: '/static/members/물류팀_김영훈.jpg',
    },
    {
      department: '물류팀',
      position: '팀원',
      name: '심다영',
      img: '/static/members/물류팀_심다영.jpg',
    },
    {
      department: '물류팀',
      position: '팀원',
      name: '이시우',
      img: '/static/members/물류팀_이시우.jpg',
    },
    {
      department: '물류팀',
      position: '팀원',
      name: '김기원',
      img: '/static/members/물류팀_김기원.jpg',
    },
    {
      department: '물류팀',
      position: '팀원',
      name: '김상태',
      img: '/static/members/물류팀_김상태.jpg',
    },
    {
      department: '물류팀',
      position: '팀원',
      name: '정경학',
      img: '/static/members/물류팀_정경학.jpg',
    },
    {
      department: '영업관리팀',
      position: '팀장',
      name: '김영삼',
      img: '/static/members/영업관리팀_김영삼.jpg',
    },
    {
      department: '영업관리팀',
      position: '팀원',
      name: '이미라',
      img: '/static/members/영업관리팀_이미라.jpg',
    },
    {
      department: '영업관리팀',
      position: '팀원',
      name: '정용현',
      img: '/static/members/영업관리팀_정용현.jpg',
    },
    {
      department: '영업관리팀',
      position: '팀원',
      name: '김문수',
      img: '/static/members/영업관리팀_김문수.jpg',
    },
    {
      department: '영업관리팀',
      position: '팀원',
      name: '김승배',
      img: '/static/members/영업관리팀_김승배.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀장',
      name: '최효승',
      img: '/static/members/원격지원팀_최효승.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '임승현',
      img: '/static/members/원격지원팀_임승현.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '박규호',
      img: '/static/members/원격지원팀_박규호.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '박명갑',
      img: '/static/members/원격지원팀_박명갑.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '이정대',
      img: '/static/members/원격지원팀_이정대.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '이한근',
      img: '/static/members/원격지원팀_이한근.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '정성기',
      img: '/static/members/원격지원팀_정성기.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '하태준',
      img: '/static/members/원격지원팀_하태준.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '김윤형',
      img: '/static/members/원격지원팀_김윤형.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '김선미',
      img: '/static/members/원격지원팀_김선미.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '김양순',
      img: '/static/members/원격지원팀_김양순.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '서현정',
      img: '/static/members/원격지원팀_서현정.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '신경진',
      img: '/static/members/원격지원팀_신경진.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '박재혁',
      img: '/static/members/원격지원팀_박재혁.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '문종헌',
      img: '/static/members/원격지원팀_문종헌.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '강우현',
      img: '/static/members/원격지원팀_강우현.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '성준호',
      img: '/static/members/원격지원팀_성준호.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '주재형',
      img: '/static/members/원격지원팀_주재형.jpg',
    },
    {
      department: '원격지원팀',
      position: '팀원',
      name: '김양화',
      img: '/static/members/원격지원팀_김양화.jpg',
    },
    {
      department: '파트너사업팀',
      position: '팀장',
      name: '이영수',
      img: '/static/members/파트너사업팀_이영수.jpg',
    },
    {
      department: '파트너사업팀',
      position: '팀원',
      name: '황선혜',
      img: '/static/members/파트너사업팀_황선혜.jpg',
    },
    {
      department: '파트너사업팀',
      position: '팀원',
      name: '윤인애',
      img: '/static/members/파트너사업팀_윤인애.jpg',
    },
    {
      department: '회계팀',
      position: '팀장',
      name: '김진영',
      img: '/static/members/회계팀_김진영.jpg',
    },
    {
      department: '회계팀',
      position: '팀원',
      name: '장은희',
      img: '/static/members/회계팀_장은희.jpg',
    },
    {
      department: '회계팀',
      position: '팀원',
      name: '조주용',
      img: '/static/members/회계팀_조주용.jpg',
    },
    {
      department: 'tBoard개발팀',
      position: '팀장',
      name: '홍민기',
      img: '/static/members/tBoard개발팀_홍민기.jpg',
    },
    {
      department: 'tBoard개발팀',
      position: '팀원',
      name: '최지현',
      img: '/static/members/tBoard개발팀_최지현.jpg',
    },
    {
      department: 'tBoard개발팀',
      position: '팀원',
      name: '문병수',
      img: '/static/members/tBoard개발팀_문병수.jpg',
    },
    {
      department: 'tBoard개발팀',
      position: '팀원',
      name: 'Jordy Ruiter',
      img: '/static/members/tBoard개발팀_조르디.jpg',
    },
    {
      department: '홍보팀',
      position: '팀원',
      name: '이의현',
      img: '/static/members/홍보팀_이의현.jpg',
    },
    {
      department: '수원지사',
      position: '지사장',
      name: '오진택',
      img: '/static/members/수원지사_오진택.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀장',
      name: '문현석',
      img: '/static/members/기술지원팀_문현석.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀원',
      name: '박지훈',
      img: '/static/members/기술지원팀_박지훈.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀원',
      name: '이길모',
      img: '/static/members/기술지원팀_이길모.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀원',
      name: '김형준',
      img: '/static/members/기술지원팀_김형준.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀원',
      name: '조상범',
      img: '/static/members/기술지원팀_조상범.jpg',
    },
    {
      department: '인천지사',
      position: '지사장',
      name: '박재신',
      img: '/static/members/인천지사_박재신.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀장',
      name: '채수근',
      img: '/static/members/기술지원팀_채수근.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀원',
      name: '김준환',
      img: '/static/members/기술지원팀_김준환.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀원',
      name: '김영두',
      img: '/static/members/기술지원팀_김영두.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀원',
      name: '이덕연',
      img: '/static/members/기술지원팀_이덕연.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀원',
      name: '임영근',
      img: '/static/members/기술지원팀_임영근.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀원',
      name: '안갑현',
      img: '/static/members/기술지원팀_안갑현.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀원',
      name: '곽두현',
      img: '/static/members/기술지원팀_곽두현.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀원',
      name: '박기욱',
      img: '/static/members/기술지원팀_박기욱.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀원',
      name: '문범균',
      img: '/static/members/기술지원팀_문범균.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀원',
      name: '김수한',
      img: '/static/members/기술지원팀_김수한.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀원',
      name: '윤성용',
      img: '/static/members/기술지원팀_윤성용.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀원',
      name: '김수민',
      img: '/static/members/기술지원팀_김수민.jpg',
    },
    {
      department: '기술지원팀',
      position: '팀원',
      name: '이가을',
      img: '/static/members/기술지원팀_이가을.jpg',
    },
    {
      department: '영업관리팀',
      position: '팀장',
      name: '박인성',
      img: '/static/members/영업관리팀_박인성.jpg',
    },
    {
      department: '영업관리팀',
      position: '팀원',
      name: '김정훈',
      img: '/static/members/영업관리팀_김정훈.jpg',
    },
    {
      department: '영업관리팀',
      position: '팀원',
      name: '연응혁',
      img: '/static/members/영업관리팀_연응혁.jpg',
    },
    {
      department: '기술/영업팀',
      position: '지사장',
      name: '김철',
      img: '/static/members/기술영업팀_김철.jpg',
    },
    {
      department: '기술/영업팀',
      position: '팀원',
      name: '이두열',
      img: '/static/members/기술영업팀_이두열.jpg',
    },
    {
      department: '기술/영업팀',
      position: '팀원',
      name: '성기화',
      img: '/static/members/기술영업팀_성기화.jpg',
    },
    {
      department: '기술/영업팀',
      position: '팀원',
      name: '최재원',
      img: '/static/members/기술영업팀_최재원.jpg',
    },
    {
      department: '기술/영업팀',
      position: '팀원',
      name: '김지현',
      img: '/static/members/기술영업팀_김지현.jpg',
    },
    {
      department: '기술/영업팀',
      position: '팀원',
      name: '이명건',
      img: '/static/members/기술영업팀_이명건.jpg',
    },
    {
      department: '경영지원팀',
      position: '팀원',
      name: '최은경',
      img: '/static/members/경영지원팀_최은경.jpg',
    },
    {
      department: '경영지원팀',
      position: '팀원',
      name: '이지현',
      img: '/static/members/경영지원팀_이지현.jpg',
    },
    {
      department: '전략사업팀',
      position: '팀장',
      name: '이규현',
      img: '/static/members/전략사업팀_이규현.jpg',
    },
    {
      department: '전략사업팀',
      position: '팀원',
      name: '윤도규',
      img: '/static/members/전략사업팀_윤도규.jpg',
    },
    {
      department: '전략사업팀',
      position: '팀원',
      name: '임정호',
      img: '/static/members/전략사업팀_임정호.jpg',
    },
    {
      department: '전략사업팀',
      position: '팀원',
      name: '신직수',
      img: '/static/members/전략사업팀_신직수.jpg',
    },
    {
      department: '상품기획팀',
      position: '팀원',
      name: '신재우',
      img: '/static/members/상품기획팀_신재우.jpg',
    },
    {
      department: '상품기획팀',
      position: '팀원',
      name: '방진호',
      img: '/static/members/상품기획팀_방진호.jpg',
    },
    {
      department: '상품기획팀',
      position: '팀원',
      name: '김병환',
      img: '/static/members/상품기획팀_김병환.jpg',
    },
  ],
};
